name: humedales_publicacion_arcgis

channels:
  - esri
  - conda-forge
  - defaults

dependencies:
  # ==========================================================
  # PYTHON
  # ==========================================================
  - python=3.11
  - pip

  # ==========================================================
  # ARCGIS ONLINE / ARCGIS PORTAL
  # ==========================================================
  - arcgis

  # ==========================================================
  # UTILIDADES
  # ==========================================================
  - requests

  # ==========================================================
  # DEPENDENCIAS COMPLEMENTARIAS VÍA PIP
  # ==========================================================
  - pip:
      # Actualmente no se requieren dependencias adicionales vía pip.
      []
